name: Создание приложения

on:
- push

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps: 
     - run: echo "Начало выполнения"
     - run: ls
     - run: cd ..
     - run: pwd
     - run: cd ..
     - run: npm run build
